apiVersion: apps/v1
kind: Deployment
metadata:
  name: api1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api1
  template:
    metadata:
      labels:
        app: api1
    spec:
      containers:
      - name: api1
        image: node_api_1:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 4000
        
---

apiVersion: v1
kind: Service
metadata:
  name: api-service
  #namespace: default

spec:
  selector:
    app: api1
  type: NodePort
  ports:
  - port: 4000 
    targetPort:  4000
    nodePort: 30088
